name: electron-snap-test
version: '0.1'
summary: Hello World Electron app
description: |
  Simple Hello World Electron app as an example
base: core18
grade: stable
confinement: strict

environment:
  XWAYLAND_FULLSCREEN_WINDOW_HINT: window_role="browser-window"

parts:
  electron-helloworld:
    after: [desktop-gtk3, xwayland-kiosk-helper]
    plugin: dump
    source: ./SnapTest/bin/Desktop/
    organize:
      'linux-unpacked/*' : bin/app/
    stage-packages:
      - libasound2
      - libgconf-2-4
      - libnss3
      - libxss1
      - libx11-xcb1
      - libxtst6
      - libdrm2
      - libgbm1
      - libc6
      - libgcc1
      - libgssapi-krb5-2
      - libstdc++6
      - zlib1g
      - libssl1.1
#      - libicu66
      - libxcomposite1
      - libxrandr2
# GTK
      # - libxkbcommon0  # XKB_CONFIG_ROOT
      # - libxkbcommon-x11-0
      # - ttf-ubuntu-font-family
      # - dmz-cursor-theme
      # - light-themes
      # - adwaita-icon-theme
      # - gnome-themes-standard
      # - shared-mime-info
      # - libgtk-3-0
      # - libgdk-pixbuf2.0-0
      # - libglib2.0-bin
      # - libgtk-3-bin
      # - unity-gtk3-module
      # - libappindicator3-1
      # - locales-all
      # - xdg-user-dirs
      # - ibus-gtk3
      # - libibus-1.0-5

  desktop-gtk3:
    build-packages:
      - build-essential
      - libgtk-3-dev
    make-parameters:
      - FLAVOR=gtk3
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk3
      - libibus-1.0-5
      - fcitx-frontend-gtk3

  xwayland-kiosk-helper:
    plugin: cmake
    source: https://github.com/MirServer/xwayland-kiosk-helper.git
    build-packages: [ build-essential ]
    stage-packages: [ xwayland, i3, libegl1-mesa, libgl1-mesa-glx ]

apps:
  electron-snap-test:
    daemon: simple
    restart-condition: always
    command: desktop-launch xwayland-kiosk-launch $SNAP/bin/app/snap-test --no-sandbox
    plugs:
      - browser-support
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - mount-observe
      - network
      - network-bind
      - opengl
      - pulseaudio
      - wayland
