name: electron-snap-test
version: '0.1'
summary: Hello World Electron app
description: |
  Simple Hello World Electron app as an example
base: core20
grade: stable
confinement: strict

package-repositories:
  - type: apt
    formats: [deb]
    components: [main]
    suites: [focal]
    key-id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
    url: https://packages.microsoft.com/ubuntu/20.04/prod

parts:
  electron-helloworld:
    plugin: dump
    source: ./SnapTest/bin/Desktop/
    organize:
      'linux-unpacked/*' : bin/app/
    stage-packages:
      - libasound2
      - libgconf-2-4
      - libnss3
      - libxss1
      - libxtst6
      - libdrm2
      - libgbm1
      - libx11-xcb1
      - libc6
      - libgcc1
      - libgssapi-krb5-2
      - libstdc++6
      - zlib1g
      - libssl1.1
      - libicu66
      - libxcomposite1
      - libxrandr2
      - libappindicator3-1
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin 
      - mesa-utils
    stage-snaps: [mir-kiosk-x11]

apps:
  electron-snap-test:
    command-chain:
      - env-setup
    command: usr/local/bin/x11_kiosk_launch $SNAP/bin/app/snap-test --no-sandbox
    plugs:
      - browser-support
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - mount-observe
      - network
      - network-bind
      - opengl
      - pulseaudio
      - wayland

layout:
  /usr/share/X11:
    bind: $SNAP/usr/share/X11
  /usr/bin/xkbcomp:
    symlink: $SNAP/usr/bin/xkbcomp
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /etc/fonts:
    bind: $SNAP/etc/fonts